services:
  - type: web
    name: trending-news-app
    env: node
    plan: free
    region: oregon
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    branch: main
    routes:
      - type: static
        path: /